packaging_format = 2

id = "domoticz"
name = "Domoticz"
description.en = "Home automation system that lets you monitor and configure miscellaneous devices"
description.fr = "Logiciel de domotique qui vous permet de configurer un grand nombre d'appareils"

version = "2023.1~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://domoticz.com/"
admindoc = "https://www.domoticz.com/wiki/Main_Page"
userdoc = "https://www.domoticz.com/DomoticzManual.pdf"
code = "https://github.com/domoticz/domoticz"
cpe = "cpe:2.3:a:domoticz:domoticz"
fund = "https://www.paypal.com/donate?token=rF_gUybGmQGia_jzLfu3vkeXRqYLRV-v-BxCTylrTsEN4mB-nDdSVQhg3a-I9LkiqORq70Gtxbo6rq3r&locale.x=US"

[integration]
yunohost = ">= 11.1.11"
architectures = "all"
multi_instance = false
ldap = false 
sso = false 
disk = "100M" 
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/domoticz"

    [install.init_main_permission]
    help.fr = "Attention, cette application n'a pas de gestion d'utilisateur par défaut, si vous la mettez public, n'importe qui y aura accès!"
    help.en = "Beware, there is no user management by default. If it's set as public, anyone will have access!"
    type = "group"
    default = "all_users"

    [install.mqtt_domain]
    ask.fr = "Domaine MQTT"
    ask.en = "MQTT domain"
    help.fr = "Domaine pour le serveur MQTT. Remettez le domaine principal si vous ne souhaitez pas l'utiliser. Lire la documentation pour plus d'informations"
    help.en = "MQTT server domain. Set the main domain if you don't wish to use it. See the doc for more info"
    type = "domain"
    optional = true

[resources]
    [resources.system_user]

    [resources.install_dir]
	dir = /opt/yunohost/__APP__
	
    [resources.permissions]
    main.url = "/"
    
    api.url = "/_api/__APP_"
    api.show_title = false
    

    [resources.ports]
    main.default = 8080
    #to be checked if it can become conditionnal
    #mqtt.default = 1883
    #mqtt_websocket.default = 8883

    [resources.apt]
    packages = "libudev-dev, python3-dev, libcurl4, libusb-0.1-4"

        #[[resources.apt.extras]]
        #repo = "deb https://repo.mosquitto.org/debian buster main"
        #key = "http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key"
        #packages = "#FIXME#$extra_pkg_dependencies