test_format = 1.0

#without Mosquitto
[default]
#Adding domain even if not used : snapshot are reused and may require domain to work
    preinstall = """
    set -euxo pipefail
    yunohost domain add mqtt.domain.tld
    """

    preupgrade = """
    set -euxo pipefail
    yunohost app setting domoticz mqtt_domain -v sub.domain.tld
    """

    args.mqtt_domain="sub.domain.tld"

    test_upgrade_from.a96510c.name = "last packaging V1"
    test_upgrade_from.a96510c.args.mqtt_domain="sub.domain.tld"
    test_upgrade_from.a96510c.args.domain="sub.domain.tld"
    test_upgrade_from.a96510c.args.path="/domoticz"

    test_upgrade_from.f8dbadb.name = "2024.2 packagingv2"
    test_upgrade_from.f8dbadb.args.mqtt_domain="sub.domain.tld"
    test_upgrade_from.f8dbadb.args.domain="sub.domain.tld"
    test_upgrade_from.f8dbadb.args.path="/domoticz"

[With_Mosquitto_upgrade_with_mosquitto]
    preinstall = """
    set -euxo pipefail
    yunohost domain add mqtt.domain.tld
    """

    args.mqtt_domain="mqtt.domain.tld"
    
    exclude = ["package_linter"]

    test_upgrade_from.a96510c.name = "last packaging v1 with mosquitto"
    test_upgrade_from.a96510c.args.mqtt_domain="mqtt.domain.tld"
    test_upgrade_from.a96510c.args.domain="sub.domain.tld"
    test_upgrade_from.a96510c.args.path="/domoticz"

    test_upgrade_from.f8dbadb.name = "2024.2 packagingv2 with mosquitto"
    test_upgrade_from.f8dbadb.args.mqtt_domain="mqtt.domain.tld"
    test_upgrade_from.f8dbadb.args.domain="sub.domain.tld"
    test_upgrade_from.f8dbadb.args.path="/domoticz"

[Without_Mosquitto_upgrade_with_mosquitto]
    preinstall = """
    set -euxo pipefail
    yunohost domain add mqtt.domain.tld
    """

    preupgrade = """
    set -euxo pipefail
    yunohost app setting domoticz mqtt_domain -v mqtt.domain.tld
    """

    args.mqtt_domain="sub.domain.tld"
    only = ["upgrade","upgrade.a96510c"]

    test_upgrade_from.a96510c.name = "last packaging v1 without mosquitto"
    test_upgrade_from.a96510c.args.mqtt_domain="sub.domain.tld"
    test_upgrade_from.a96510c.args.domain="sub.domain.tld"
    test_upgrade_from.a96510c.args.path="/domoticz"
    
    test_upgrade_from.f8dbadb.name = "2024.2 packagingv2 without mosquitto"
    test_upgrade_from.f8dbadb.args.mqtt_domain="sub.domain.tld"
    test_upgrade_from.f8dbadb.args.domain="sub.domain.tld"
    test_upgrade_from.f8dbadb.args.path="/domoticz"
    